### PR TITLE
Add Chroma Palette Chrome extension.

### PR DESCRIPTION
**Pull request by bymayanksingh**
Chroma Palette 🎨 is a chrome extension to extract, pick and manage the dominant color palette from the visible area of any webpage or pick and manage specific color palettes using an uploaded image.

### CODE REVIEW

**Comment by bymayanksingh** [comment]
@ajayts07 can you review & merge? Thanks.

**Review by ajayts07 — APPROVED** [review]
Add the chrome Extension

**Comment by ajayts07** [comment]
If you liked the collection, kindly Give us a Star to the GitHub repo before contributing :)

**Comment by bymayanksingh** [comment]
> If you liked the collection, kindly Give us a Star to the GitHub repo before contributing :)

Hey, just starred the repo :)

**Pull request merged**
